### ISSUE TITLE
Breaking wildcard module and not saving en version of standard fields

### ISSUE THREAD

**Issue by devstack** [kamsar/Unicorn#92] opened 2015-12-07 20:56 UTC
I'm installing the Wildcard Module fo Sitecore v8.1. All is working fine.. items appear to be serializing but when I sync it breaks. I receive messages in the log.. example below:

[U] master:/sitecore/system/Settings/Rules/Wildcards (3875bd5f-da54-48ff-9464-301ba615e5be)
> Orphaned version en#1 (source)
* [D] en#1

Appears to be related to not saving the en version of the standard values fields of an item. When I serialize using native sitecore it works fine.

I'm currently using Unicorn.Default.config

**Comment by kamsar** [comment] 2015-12-08 03:56
The wildcard module as in [this one](https://marketplace.sitecore.net/en/Modules/Wildcard_module.aspx) that's from 6.5 days?

What Unicorn version and Rainbow version are you running? What steps did you use to install the module and get its items serialized?

**Comment by devstack** [comment] 2015-12-08 08:46
Yes that's the one - there doesn't appear to be an updated one but it seems
to work with 8.1

I followed the manual installation instructions for Unicorn on the github
page (maybe I should have used nuget package).. so I should have the latest
clone of both unicorn and rainbow as of approx 3 weeks ago.

I installed the module in Sitecore admin -> Control Panel -> Install
Package option. Serialization happens automatically whenever I change any
data in the sitecore master database.

Thanks for your help Kam - it's appreciated.

On Tue, Dec 8, 2015 at 3:56 AM, Kam Figy <notifications@github.com> wrote:

> The wildcard module as in this one
> <https://marketplace.sitecore.net/en/Modules/Wildcard_module.aspx> that's
> from 6.5 days?
>
> What Unicorn version and Rainbow version are you running? What steps did
> you use to install the module and get its items serialized?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamsar/Unicorn/issues/92#issuecomment-162751875>.
>



-- 

*Tom Miller*
Director
Devstack Consultancy Ltd
tom@devstack.co.uk
+44 7810 387300

**Comment by kamsar** [comment] 2015-12-11 06:39
Hmm. This wildcards item was installed by the package yes?

What happens if you reserialize it, do you get the language version in the yaml then?

**Comment by kamsar** [comment] 2015-12-11 20:23
I have a hypothesis that it's specifically related to items that are installed by a package or an update package. The fields are missed.

**Comment by devstack** [comment] 2015-12-13 07:56
Yes that seems to be what is happening. Had lots of errors showing in the
log when I installed Commerce Connect. It took me ages to fix then excluded
all items from my config to prevent it from happening again.

On Fri, Dec 11, 2015 at 8:23 PM, Kam Figy <notifications@github.com> wrote:

> I have a hypothesis that it's specifically related to items that are
> installed by a package or an update package. The fields are missed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamsar/Unicorn/issues/92#issuecomment-164039454>.
>



-- 

*Tom Miller*
Director
Devstack Consultancy Ltd
tom@devstack.co.uk
+44 7810 387300

**Comment by kamsar** [comment] 2015-12-13 09:56
There seems to be an issue with package installed items specifically. It
looks like sitecore 'builds them up' with multiple save calls each with
_partial_ item data included.

First off wtf :) I may have to alter the way saves happen as everywhere
else all item data is available.

As a workaround for now when installing a package or update package sync
before and reserialize right after.

**Comment by kamsar** [comment] 2015-12-14 05:31
Hi @devstack I was able to reproduce the (very odd) behavior when installing packages and like the Borg, adapt to it. Essentially now when items are saved the changes made in Sitecore are merged with any existing data on disk, so partial data will not cause any data to be lost from disk.

This technique is very similar to Sitecore's own SQL data provider guts, which are totally reliant on the `ItemChanges` and not the `Item` as Unicorn was. Unicorn 2.x was not affected by this because it did not have transparent sync and could thus rely on all items being present in the database.

Unicorn 3.1.0-beta02 and Rainbow 1.1-beta02 are now on NuGet for your perusal. Note that the YAML format emitted by Rainbow 1.1-b2 and later cannot be understood by Rainbow 1.0.x (though 1.1.x understands 1.0.x formats just fine). So you may wish to revert items when testing is done, unless you want to stick with the beta.

**Comment by devstack** [comment] 2015-12-14 16:34
Thanks so much for your help Kam. It's very much appreciated!

On Mon, Dec 14, 2015 at 5:31 AM, Kam Figy <notifications@github.com> wrote:

> Hi @devstack <https://github.com/devstack> I was able to reproduce the
> (very odd) behavior when installing packages and like the Borg, adapt to
> it. Essentially now when items are saved the changes made in Sitecore are
> merged with any existing data on disk, so partial data will not cause any
> data to be lost from disk.
>
> This technique is very similar to Sitecore's own SQL data provider guts,
> which are totally reliant on the ItemChanges and not the Item as Unicorn
> was. Unicorn 2.x was not affected by this because it did not have
> transparent sync and could thus rely on all items being present in the
> database.
>
> Unicorn 3.1.0-beta02 and Rainbow 1.1-beta02 are now on NuGet for your
> perusal. Note that the YAML format emitted by Rainbow 1.1-b2 and later
> cannot be understood by Rainbow 1.0.x (though 1.1.x understands 1.0.x
> formats just fine). So you may wish to revert items when testing is done,
> unless you want to stick with the beta.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kamsar/Unicorn/issues/92#issuecomment-164346423>.
>



-- 

*Tom Miller*
Director
Devstack Consultancy Ltd
tom@devstack.co.uk
+44 7810 387300

**Comment by kamsar** [comment] 2016-01-27 05:43
This is fixed in 3.1 final.

**Closed by kamsar** 2016-01-27 05:43 UTC
Labels: bug, fix-pending
