### ISSUE TITLE
Show "bad" config on sync page

### ISSUE THREAD

**Issue by ekapus** [kamsar/Unicorn#178] opened 2016-10-04 12:46 UTC
In Habitat/Helix solutions, there are often a LOT of configs to be synced. Luckily, the checkboxes make quick work of this. 

Unless, of course, there's a bad config in there. 

However, trying to figure out the culprit that is causing the checkboxes to go away is difficult because you have to manually sync each project until you get to the offender. 

It would be awesome if a config that's failing validation would be somehow noted on the main sync page instead of only making the checkboxes go away. Sadly, Mr. Yuk is trademarked, but I'm sure you'll come up with something fun.

**Comment by kamsar** [comment] 2016-10-04 14:44
This was - at least theoretically - fixed several releases ago. Give it a shot with the latest RC version and see if you're still seeing the issue. If you are, I'll need specific details about what was wrong and how to reproduce it because yes, any errors are supposed to trigger global banners not just the removal of checkboxes.

**Comment by ekapus** [comment] 2016-10-04 15:46
Cool, I'll check it out. I'm still using 3.11.

**Comment by kamsar** [comment] 2016-10-06 01:39
Closing this one. Feel free to reopen if upgrading does not solve your problem.

**Closed by kamsar** 2016-10-06 01:39 UTC
Labels: bug, no-reproduction
