### ISSUE TITLE
Template's standard value for checkbox not synced to DB when overriding ancestor by unchecking

### ISSUE THREAD

**Issue by thesoftwarejedi** [kamsar/Unicorn#121] opened 2016-02-29 19:52 UTC
*We are using the latest version of Unicorn.*
Version 3.1.2.0: 

Similar to #74, but perhaps a different edge case, involving inheritance of standard values.  

To reproduce:

- Create template BaseTemplate with a field MyField of checkbox type.  
- Create standard values for BaseTemplate.
- Assign the value of "checked" (1) to MyField in the standard values of BaseTemplate (using sitecore rocks or content editor).
- Create another template DerivedTemplate, with the BaseTemplate as one of its base templates.
- Create standard values for DerivedTemplate.
- Initially, the standard value for MyField will be checked, and a *serialization will exclude DerivedTemplate MyField* since its using the default.  Verify by serializing.  I believe this is correct behavior.
- Uncheck MyField in DerivedTemplate's standard values, and save.  Note, the number of times you check save, uncheck save has no bearing on the next step.
- *Serialization will now serialize MyField in DerivedTemplate's standard values yml - as a blank value*

The above behavior seems correct, with the possibility that it should serialize as "0".

- *now delete the sitecore database, and start with a fresh master*
- sync the yml files from above into the fresh database.
- note: *MyField in DerivedTemplate's standard values is set to checked, and marked as using standard values (from BaseTemplate)*  This is incorrect and inconsistent from where it was serialized from.
- change the yml file to have an explicit "0" for MyField in DerivedTemplate's standard values
- sync the yml files into the fresh database.
- Now it was synced correctly, and displays as uncked in the derived template

Conclusion - I believe this is a problem with sync and standard values.  It appears related to #74, but that was fixed in November.  Perhaps related to the standard values being inherited.

**Comment by thesoftwarejedi** [comment] 2016-02-29 19:59
Note that explicitly setting the template's std value in the yml to "0" is a valid workaround for us for the issue.

**Comment by Eldblom** [comment] 2016-03-07 04:14
+1 on this issue. We keep running into this one in Habitat.

**Comment by agehrke** [comment] 2016-03-17 09:57
I would say that this is actually caused by how Sitecore stores the value for a `Sitecore.Data.Fields.CheckboxField`. [Rainbow](https://github.com/kamsar/Rainbow/), which handles the serialization/deserialization just uses the field value directly. See [`YamlFieldValue.LoadFrom()`](https://github.com/kamsar/Rainbow/blob/9f4f00fb425bced394bd36f59d55ed319e4835cf/src/Rainbow.Storage.Yaml/OutputModel/YamlFieldValue.cs#L20).

I think the root issue is that with a CheckboxField on derived template, you have no way of knowing whether the standard values on the derived template has actively checked/unchecked the checkbox field value set by the base template. I think what you need is the tristate field.

**Comment by kamsar** [comment] 2016-03-19 04:30
BTW, an unchecked checkbox Sitecore actually uses a blank value for. Seems like yes it should be 0, and the value of 0 works, but the default is blank.

**Comment by kamsar** [comment] 2016-03-19 05:00
This appears to be related actually to the order items are loaded in. If I remove and recreate just derived's standard values it behaves as expected (using the significant empty value support from #74).

But I can reproduce if I'm creating both templates at the same time.

**Comment by kamsar** [comment] 2016-03-19 05:11
Diagnosis: this is caused by the tree being loaded breadth-first, instead of depth-first.

Essentially this issue is reproducible iff the whole template is being loaded, including critically the field(s) in question.

The problem is that the _standard values items are loading before the template fields_. This means that when they load, the template does not yet have fields so we have nothing to compare against for significant empty values.

If you have the templates and fields existing, then load the standard values afterwards the values are fine.

**Comment by kamsar** [comment] 2016-03-19 06:28
The solution to this ended up being two methods:

1) To make the load order more sane, the retryer is used to push the standard values items to the end of the sync. This guarantees all of their fields exist prior to their sync. However, this does not help this specific bug _if the derived template loads before the base template_ (because the base template's standard values does not yet exist, it would again be considered a default value and left unset because it was equal to standard value).

2) to get around the 'what order are your templates' issue, I have added to the default Unicorn configuration a field formatter and comparer for checkboxes. This forces Unicorn to store all checkbox values as either 0 or 1, giving them an explicit hook to say that negative values are NOT standard values if a derived template loads first.

(2) does mean that after saving a falsy checkbox the next sync will have a 'change' as it normalizes the database value to 0 instead of blank. IMO, this is just a bonus and adds sanity.

**Comment by kamsar** [comment] 2016-03-21 04:16
This should be fixed in Unicorn 3.1.5-beta01, available on NuGet.

**Comment by kamsar** [comment] 2016-03-24 04:24
Unicorn 3.1.5 has been released with this fix. Closing the issue. If you find it again, please reopen.

**Closed by kamsar** 2016-03-24 04:24 UTC
Labels: bug, fix-pending

**Comment by shafaqat309** [comment] 2017-10-09 02:46
I cant get this working, I am using Unicorn 3.2.0
The derived template does not show checkbox field in yml file.
Actual template has checkbox field with value 1.
