### ISSUE TITLE
Unicorn not deserializing different item versions

### ISSUE THREAD

**Issue by MrSnappingTurtle** [kamsar/Unicorn#188] opened 2016-11-11 03:20 UTC
Hey,

I was recently working on creating different versions of items in another language. For this example, I made a Spanish version and removed the original English version. This resulted in me having the following `.yml` file:

```yml
---
ID: "8eb2cc77-bd5e-4555-b23a-8f3796cb858f"
Parent: "cd89c372-fcbf-44f0-aa9c-5b6153c68ddc"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/content/somesite-com/spain"
DB: master
Languages:
- Language: "es-ES"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161110T150125
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
```

As you can see, it seems like it was serialized correctly, there is only one version, and it is the Spanish one. However, when the code was deserialized on another device, the Spanish version is missing, and only an English version is present:

![spanish](https://cloud.githubusercontent.com/assets/8148243/20203300/f8191024-a77a-11e6-8f5e-696ff4870076.PNG)

This doesn't seem to make sense as it is ignoring the contents of the `.yml` file. I saw the following output in the console:

```
[U] master:/sitecore/content/somesite-com/spain (8eb2cc77-bd5e-4555-b23a-8f3796cb858f)
> Orphaned version en#1 (source)
> Orphaned version en#1 (source)
> Orphaned version en#1 (source)
...
```

Any idea what might be going on? This is using Sitecore 7.5 and Unicorn 3.2.0. Thanks!

**Comment by kamsar** [comment] 2016-11-11 05:33
Try it with 3.3.1. There are a lot of fixes in that version.

**Comment by MrSnappingTurtle** [comment] 2016-11-11 18:15
Is `Ranbow.Core.1.4.0` usable with .NET 4.5? We don't have the option to update it. Is there any way around this?

```powershell
PM> Install-Package Unicorn -Version 3.3.1
Attempting to gather dependency information for package 'Unicorn.3.3.1' with respect to project 'website', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'Unicorn.3.3.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Unicorn.3.3.1'
Resolved actions to install package 'Unicorn.3.3.1'
Removed package 'MicroCHAP.1.2.1' from 'packages.config'
Successfully uninstalled 'MicroCHAP.1.2.1' from website
Removed package 'Rainbow.1.3.1' from 'packages.config'
Successfully uninstalled 'Rainbow.1.3.1' from website
Removed package 'Rainbow.Core.1.3.1' from 'packages.config'
Successfully uninstalled 'Rainbow.Core.1.3.1' from website
Removed package 'Rainbow.Storage.Sc.1.3.1' from 'packages.config'
Successfully uninstalled 'Rainbow.Storage.Sc.1.3.1' from website
Removed package 'Rainbow.Storage.Yaml.1.3.1' from 'packages.config'
Successfully uninstalled 'Rainbow.Storage.Yaml.1.3.1' from website
Removed package 'Unicorn.Core.3.2.0' from 'packages.config'
Successfully uninstalled 'Unicorn.Core.3.2.0' from website
Adding package 'MicroCHAP.1.2.2.2' to folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'MicroCHAP.1.2.2.2' to folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'MicroCHAP.1.2.2.2' to 'packages.config'
Successfully installed 'MicroCHAP 1.2.2.2' to website
Install failed. Rolling back...
Package 'Rainbow.Core.1.4.0' does not exist in project 'website'
Removed package 'MicroCHAP.1.2.2.2' from 'packages.config'
Package 'Unicorn.Core.3.2.0' already exists in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'Unicorn.Core.3.2.0' to 'packages.config'
Package 'Rainbow.Storage.Yaml.1.3.1' already exists in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'Rainbow.Storage.Yaml.1.3.1' to 'packages.config'
Package 'Rainbow.Storage.Sc.1.3.1' already exists in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'Rainbow.Storage.Sc.1.3.1' to 'packages.config'
Package 'Rainbow.Core.1.3.1' already exists in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'Rainbow.Core.1.3.1' to 'packages.config'
Package 'Rainbow.1.3.1' already exists in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'Rainbow.1.3.1' to 'packages.config'
Package 'MicroCHAP.1.2.1' already exists in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Added package 'MicroCHAP.1.2.1' to 'packages.config'
Package 'Rainbow.Core.1.4.0' does not exist in folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Removing package 'MicroCHAP.1.2.2.2' from folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Removed package 'MicroCHAP.1.2.2.2' from folder 'C:\Users\Administrator\projects\some-sites\webcms2-core-mirror-colddata\dotnet\core\packages'
Install-Package : Could not install package 'Rainbow.Core 1.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly referenc
es or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  Unicorn -Version 3.3.1
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 ```

**Comment by kamsar** [comment] 2016-11-11 21:40
.NET 4.5.0 is out of support from MS. 4.5.2 is supported and is a drop in
replacement.

You should be able to compile from source against 4.5 and earlier sitecore
assemblies but I have no plans to distribute a package with that
configuration.

**Comment by MrSnappingTurtle** [comment] 2016-11-13 21:17
I've updated to 4.5.2 and installed 3.3.1. Still having the same issue. Even if I try removing the `/sitecore/content/somesite-com/spain` item mentioned above and syncing again, I only get an English version. The only time the Unicorn output changed and said that it was using `es-ES` was when in Visual Studio I manually removed the Enlgish version and created a Spanish version. The `.yml` file did not change at all.

**Comment by kamsar** [comment] 2016-11-18 16:53
I just attempted to reproduce this and was unable to. Here's what I did:

* Added es-ES to my setup
* Added a new content page item
* Added an es-ES version to it
* Deleted the en version
* _At this point my yaml looks like your example above. I saved this yaml file._
* Re-added the en version and deleted the es-ES version to simulate your other environment that appears to have had only an english version
* Replaced the serialized yaml with the saved file containing only es-ES
* Ran a sync

Result: 
```
[U] master:/sitecore/content/Prototype/Home (b6811459-840f-47b1-aa79-ec47a09649d8)
> Orphaned version en#1 (source)
* [A] version es-ES#1
* [U] es-ES#1: __Created
* [U] es-ES#1: __Workflow state
* [U] es-ES#1: __Created by
* [D] en#1
* [U] en: __Display name```

The Sitecore item had also as expected removed the en version and added es-ES.

**Comment by MrSnappingTurtle** [comment] 2016-11-21 23:49
Is there anything I can do to help you replicate this issue? If it would help, I can let you control my screen and look at my environment directly. Please advise. This is a major issue impeding our translations project.

**Comment by kamsar** [comment] 2016-11-24 06:40
I would suggest compiling Unicorn from source and attaching a debugger to see what's going on. If you can find a more generally replicatable scenario that I can test with, we can fix it. Try on a fresh SIM instance as well to isolate any configuration issues you may have.

**Comment by kamsar** [comment] 2016-11-28 19:03
Are there any other unusual circumstances that could alter default behaviour (thus preventing me from reproducing)?

For example:
* Language fallback
* Event handlers
* Other data providers?

**Comment by MrSnappingTurtle** [comment] 2016-11-29 06:33
Hey, I'll try to get to your suggestions sometime this week. We're working in an inherited environment so it's completely possible something is interfering.

**Comment by MrSnappingTurtle** [comment] 2016-12-09 16:59
Hey Kam,

Sorry, I've been sidetracked by higher priority issues. I'll let you know when I have an update.

**Comment by kamsar** [comment] 2016-12-10 04:02
No problem :) I'm also keeping an eye out in daily dev for any issues like this.

**Comment by kamsar** [comment] 2017-01-25 03:23
Going to close this one for now; feel free to reopen if you find a reproduction case.

**Closed by kamsar** 2017-01-25 03:23 UTC
Labels: bug, no-reproduction
