### ISSUE TITLE
Blob values did not saved in yaml files

### ISSUE THREAD

**Issue by dashkodo** [kamsar/Unicorn#102] opened 2016-01-21 10:30 UTC
Steps to reproduce:
Configure unicorn to store items from Media library
Upload video item as blob into media library (default sitecore behavior)

Expected result: Base64 value stored in yaml file
Actual result: Blob id stored in yaml file

**Comment by kamsar** [comment] 2016-01-22 00:29
Thanks for the issue report. I was able to reproduce it and fix it. This is part of Unicorn 3.1b11, on NuGet now.

The root cause was due to the fix added in 3.1 to adapt to how Sitecore installs packages. The code to handle the partial data sent by packages was not aware of how to correctly read a blob field.

**Comment by Sivalingaamorthy** [comment] 2016-01-22 05:26
I did face similar issue, does this fix also solve this problem aswell.

master:/sitecore/media library/Globus/Portal/General Site Images/banner (217c8c69-1a69-46b5-a58d-8b684ef73811)
...Configuration\medialibrary\globus\Portal\General Site Images\banner.yml
> DeserializationException: Failed to paste item: /sitecore/media library/Globus/Portal/General Site Images/banner
> InvalidOperationException: Field 40e50ed9-ba07-4702-992e-a912738d32dc is a blob field, but it had no blob ID.

**Comment by kamsar** [comment] 2016-01-22 05:28
Yes, but you'll need to reserialize that item to get the blob id and blob
data into the yaml.

**Comment by kamsar** [comment] 2016-01-27 05:42
This is fixed in 3.1 final.

**Closed by kamsar** 2016-01-27 05:42 UTC
Labels: bug, fix-pending
