### ISSUE TITLE
Unicorn content update requires IISRESET

### ISSUE THREAD

**Issue by TheCodeKing** [kamsar/Unicorn#127] opened 2016-03-10 15:58 UTC
We are having a problem which is hard to track down. On a clean instance of Sitecore we warm the site and use Unicorn to deploy content.

If we hit the site whilst the deployment is happening and with a large number of items, we find that not all items appear in the master database. If we use the Sitecore admin page to clear caches or even manually publish they still don't appear. 

The only resolution seems to be an IISRESET. After this all items appear in both master and web. This issue appears to be intermittent, or might be that it works if the site isn't accessed whilst running.  

We are using Unicorn 3.1.4 with Sitecore 8.1 rev. 151003.

**Comment by kamsar** [comment] 2016-03-14 04:25
Are you using transparent sync?

**Comment by TheCodeKing** [comment] 2016-03-14 09:57
No not using transparent sync.We are using powershell to deploy content. It's hard to reproduce. Locally it works. On an Azure box the issue is happening consistently.

**Comment by kamsar** [comment] 2016-03-14 13:33
...and I'm guessing you know just how much fun it is to debug on Azure :)

I can't say I've seen this issue, and while I totally believe you that it occurred, without a reproduction scenario I've not got much to go on. Anything in the Sitecore logs? Maybe try disabling the Unicorn data provider, if it's loaded in Azure, and see if that makes any difference?

**Comment by kamsar** [comment] 2016-03-22 03:33
If you find a reproduction for this, please reopen this issue or a new one. For now however, I'm going to close it. With luck, some of the fixes in 3.1.5 will be the cause :)

**Closed by kamsar** 2016-03-22 03:33 UTC
Labels: bug, no-reproduction

**Comment by TheCodeKing** [comment] 2016-03-24 19:58
Seems to be resolved in recent fixes.

**Comment by TheCodeKing** [comment] 2016-08-22 20:49
This issue seems to have come back. Maybe it's because we are installing more content than previously. It still seems to be intermittent. 

After installing content via Unicorn it's sometimes not visible in the Sitecore tree until an IISRESET. We are currently using 3.2.0, but also experiencing on 3.1.5-beta0.
