### ISSUE TITLE
Issue with copying Unicorn Serialized items during deploy

### ISSUE THREAD

**Issue by t00ki** [kamsar/Unicorn#208] opened 2017-01-31 18:21 UTC
Hi,

I'm currently working on setup CI for my company project.
They used Sitecore as main CMS and we decide to use your great application for storing Sitecore items in our repo.

Issue happens when I'm trying to deploy serialized items to the server. Unicorn data folder 'Locked' by w3p.exe process and prevent deleting/coping items to it
Need to note that this is not happens every time. 
Maybe 2-3 times from 10 try of deploy.

I trying to implement this step (*it runs right after the MsWebDelpoy task complete*) with following ways:

1.  Using 'Copy' target of MsBuild, something like that:
` <Target Name="UnicornCopy">
    <Message Text="Copy ALL unicorn data" />
    <RemoveDir Directories="$(Unicorn_CopyToFolder)" />
    <ItemGroup>
      <UniFilesToCopy Include="$(UniBaseFolder)\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(UniFilesToCopy)"
        DestinationFiles="@(UniFilesToCopy -> '$(Unicorn_CopyToFolder)\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>`

Got this exception:
`[RemoveDir] C:\TeamCity\buildAgent\work\1eca835870b9b84b\src\Build\targets.proj(57, 5): error MSB3231: Unable to remove directory "{{My_Server_Path}}\Unicorn\". The directory is not empty.`

As I mentioned previously - next run goes smoothly (but also not always :) ).

2.  Using 'robocopy' MS tool with following way:
`robocopy $CopyFrom $CopyTo /MIR`

Got this bucket of exceptions as well:

```
  Waiting 30 seconds... Retrying...
  2017/01/31 19:57:44 ERROR 5 (0x00000005) Accessing Destination Directory 
c:\Unicorn
  Access is denied.
  
  Waiting 30 seconds... Retrying...
  2017/01/31 19:58:14 ERROR 5 (0x00000005) Accessing Destination Directory 
c:\Unicorn
  Access is denied.

  Waiting 30 seconds... Retrying...
  ...
  
```

3. Using powershell cmdlets:

```
Remove-Item $CopyTo\* -Recurse
Copy-Item -Path $CopyFrom* -Destination $CopyTo -Recurse
```

Got this

```
Remove-Item : Directory C:\Quintiles\Unicorn\Q2Labs Content cannot be removed because it is not empty.
  At D:\GIT\QIMS\src\Build\UnicornSync\CopyData.ps1:15 char:1
  + Remove-Item $CopyTo\* -Recurse
  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : WriteError: (C:\Quintiles\Unicorn\Q2Labs Content:DirectoryInfo) [Remove-Item], IOExcepti 
     on
      + FullyQualifiedErrorId : DirectoryNotEmpty,Microsoft.PowerShell.Commands.RemoveItemCommand
```

After all of these things I decided to disable Unicorn by adding .disable to the Unicorn config files before copy, and enable them back after copying, right before syncing. But it also doesn't help. :(
This is list of files that I'm disabling:
```
Unicorn.config
Unicorn.UI.config
Unicorn.DataProvider.config
Unicorn.Roles.DataProvider.config
```
I did my best with googling, but a lot of people said that they move Unicorn items without any issue with any of the below.

I also found @kamsar comment [here](http://andrew.lansdowne.me/2013/06/07/auto-deploy-sitecore-items-using-unicorn-and-teamcity/#comment-3), about using 'robocopy' for deploy. But as I said previously - it doesn't work for me.

This is last Sitecore 8.2 version and latest stable Unicorn version available via NuGet (3.3.2).

Any thoughts?

**Comment by kamsar** [comment] 2017-02-01 02:17
Funny you should bring this up, because I just found the cause of this last night - issues with the `FastDirectoryEnumerator` class in Rainbow :)

It will be fixed in the next release.

**Comment by t00ki** [comment] 2017-02-01 08:31
Great news, thank you!

**Comment by kamsar** [comment] 2017-02-02 04:46
Just for you, here's [Rainbow 1.4.2](https://github.com/kamsar/Rainbow/releases/tag/1.4.2)

**Comment by t00ki** [comment] 2017-02-02 16:45
You are my hero. Thank you, once again.

**Closed** 2017-02-03 06:39 UTC
Labels: bug, fix-pending
