### ISSUE TITLE
Getting Server cannot append header after HTTP headers have been sent

### ISSUE THREAD

**Issue by waaromikniet** [kamsar/Unicorn#170] opened 2016-09-08 11:46 UTC
Hi,

I am getting Server cannot append header after HTTP headers have been sent when I try to sync the roles with unicorn. Any ideas?

Regards
Danny

**Comment by kamsar** [comment] 2016-09-08 15:46
Duplicate of #155. This is fixed in the current prerelease version already.

I am assuming that you're using Sitecore 8.1U3 or 8.2. You can work around this by setting the 'X-Frame-Options' header yourself _prior to Sitecore trying to set it on request end_.

**Closed by kamsar** 2016-09-08 15:46 UTC
Labels: fix-pending
